export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export enum NotificationsActionTypes {
    UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
    REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
}
export enum LoginActionTypes {
    SIGNUP_REQUEST = 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE = 'SIGNUP_FAILURE',
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_REQUEST = 'LOGOUT_REQUEST',
    LOGOUT_FAILURE = 'LOGOUT_FAILURE',
    // REFRESH_REQUEST = 'REFRESH_REQUEST',
    // REFRESH_SUCCESS = 'REFRESH_SUCCESS',
    // REFRESH_FAILURE = 'REFRESH_FAILURE',
    // LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST',
    // LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS',
    // LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE',
    // UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST',
    // UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS',
    // UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE',
}

export enum LoginStatusActionTypes {
    LOGIN_STATUS_REQUEST = 'LOGIN_STATUS_REQUEST',
    LOGIN_STATUS_SUCCESS = 'LOGIN_STATUS_SUCCESS',
    LOGIN_STATUS_FAILURE = 'LOGIN_STATUS_FAILURE',

}
