export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export enum notificationsActionTypes {
    UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
    REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
}
export enum loginActionTypes {
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    // REFRESH_REQUEST = 'REFRESH_REQUEST',
    // REFRESH_SUCCESS = 'REFRESH_SUCCESS',
    // REFRESH_FAILURE = 'REFRESH_FAILURE',
    // LOGOUT_REQUEST = 'LOGOUT_REQUEST',
    // LOGOUT_FAILURE = 'LOGOUT_FAILURE',
    // LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST',
    // LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS',
    // LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE',
    // UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST',
    // UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS',
    // UPDATE_CURRENT_USER_FAILURE = 'UPDATE_CURRENT_USER_FAILURE',
}

